### ISSUE TITLE
Conflict between max and disjunction

### ISSUE THREAD

**Issue by jnarboux** [Deducteam/lambdapi-logics#2]
Hi,

In TFF/Nat.lp the symbol  ∨: ℕ → ℕ → ℕ;  is defined but it seems to produce a conflict with the disjunction defined in TFF/Prop.lp : constant symbol ∨ : Prop → Prop → Prop; 

For example, if I load the Nat.lp file then the following definition is not accepted anymore:
constant symbol MyT : TYPE;

constant symbol r : MyT → Prop;
constant symbol p : MyT → Prop;
constant symbol q : MyT → Prop;
constant symbol ax1 x : π( r x  ⇒  p x ∨ q x);
 It assumes ∨: ℕ → ℕ → ℕ instead of  ∨ : Prop → Prop → Prop; 

Am i missing something ?

**Comment by fblanqui** [comment]
To solve this kind of conflicts, you can prefix symbols by the right module name (TFF.Prop.∨) or open the module before (open TFF.prop). The order of require's and open's is important.
However, ∨is not a very nice notation for max anyway: I will change it. And Nat should not be in this package since this package is dedicated to logics only: I will fix this too.

**Comment by fblanqui** [comment]
@jnarboux Does it answer your questions?

**Comment by jnarboux** [comment]
Thank you Frédéric. I suggest indeed to change the notation for max.
